### ISSUE TITLE
YAML Configuration - MAC address

### ISSUE THREAD

**Issue by tiagofreire-pt** [newAM/hisensetv_hass#5]
Hi.

The MAC address needed for the yaml configuration is from the client previously authenticated or the one from the TV itself?

``` yaml
switch:
  - platform: hisensetv
    host: 10.0.0.28
    mac: ab:cd:ef:12:34:56
    name: tv
```

Thanks.
